nomecliente = input("Digite o nome do cliente: ")
diavencimento = input("Digite o dia de vencimento: ")
mesvencimento = input("Digite o mes de vencimento: ")
valorfatura = input("Digite o valor da fatura: ")
print("Olá,", nomecliente)
print("A sua fatura com vencimento em ", diavencimento, "de ", mesvencimento, "no valor de R$ ",valorfatura, "está fechada.")
