nome = str(input("Digite um nome completo: ")).strip()
print("Analisando seu nome...")
print("Seu nome em maiúsculas é {}.".format(nome.upper()))
print("Seu nome em minísculas é {}.".format(nome.lower()))
print("Seu nome tem ao todo {} letras.". format(len(nome)-nome.count(' ')))
print("Seu primeiro nome tem {} letras".format(nome.find(' ')))
separa = nome.split()
print("Seu primeiro nome é {}". format(separa[0], len(separa[0])))